[package]
name = "xcb-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[[bin]]
name = "xcb"
path = "src/main.rs"

[lints]
workspace = true

[dependencies]
clap = { version = "=4.5.48", features = ["derive", "wrap_help"] }
clap_complete = "=4.6.9"
hraness-cli-kit = { git = "https://github.com/hraness/desktop-foundation", tag = "v0.8.1", features = ["clap"] }
serde = "=1.0.229"
serde_json = "=1.0.151"
tokio = { version = "=1.47.1", features = ["rt-multi-thread", "macros", "signal", "sync", "time"] }
unicode-width = "=0.2.0"
xcb-core = { version = "0.10.3", path = "../xcb-core" }
xcb-runtime = { version = "0.10.3", path = "../xcb-runtime" }
xcb-tui = { version = "0.10.3", path = "../xcb-tui" }
zeroize = "=1.9.0"

[dev-dependencies]
rusqlite = { version = "=0.40.2", features = ["bundled"] }
