// The launch social kit as Markdown, for kb/launch/social-kit.md.
// Every line comes from ./beats and ./facts; edit those, not the output.
import { launchBeats, socialKit } from "./beats";
import { LAUNCH_STATUS, launchFacts } from "./facts";

const block = (text: string): string => ["```text", text, "```"].join("\n");
const thread = (name: string, posts: readonly string[]): string[] => [
  `## ${name}`,
  "",
  ...posts.flatMap((post, index) => [
    `Post ${index + 1} of ${posts.length}, ${[...post].length} characters`,
    "",
    block(post),
    "",
  ]),
];

export function renderSocialKitMarkdown(): string {
  const lines = [
    "# Excalibur (xcb) launch social kit",
    "",
    "Generated by `bun run launch:kit` in `site/` from `site/app/launch/beats.ts` and `site/app/launch/facts.ts`. Do not edit by hand; change the beats or facts and run it again.",
    "",
    `Posts go out from the @hraness account. The status is ${LAUNCH_STATUS}. The launch post ships noindex until an independent review scores it, so hold the posts until then. Show HN and the Product Hunt first comment are written by a person from the fact sheet below.`,
    "",
    ...thread("X thread", socialKit.x),
    ...thread("Bluesky thread", socialKit.bluesky),
    ...thread("Threads thread", socialKit.threads),
    "## LinkedIn post",
    "",
    block(socialKit.linkedin),
    "",
    "## Product Hunt",
    "",
    `Tagline: ${socialKit.productHunt.tagline}`,
    "",
    "Description:",
    "",
    block(socialKit.productHunt.description),
    "",
    `Topics: ${socialKit.productHunt.tags.join(", ")}`,
    "",
    "## Show HN and first comment fact sheet",
    "",
    ...socialKit.showHnFacts.map((fact) => `- ${fact}`),
    "",
    "## Beats",
    "",
    ...launchBeats.map((beat, index) => `${index + 1}. ${beat.headline}`),
    "",
    "## Facts and their records",
    "",
    ...Object.entries(launchFacts).map(([name, fact]) => `- ${name}: ${fact.value}. ${fact.source}`),
    "",
  ];
  return lines.join("\n");
}
