use crate::{Error, Result, digest, private, process::Pin};
use base64::Engine;
use serde::{Deserialize, Serialize};
use serde_json::{Value, json};
use std::{
    collections::BTreeSet,
    io::Read,
    path::{Path, PathBuf},
};
use xcb_core::Provider;

pub const VERSION: &str = "0.159.0";
pub const BINARY_SHA256: &str = "e89718aa1969bfc4a471277bdc4679a3a3529293de0a309909822dfd67ddb77a";
/// Sorted relative schema path, NUL, generated bytes, NUL for each JSON file
/// written by `codex app-server generate-json-schema --experimental`.
pub const SCHEMA_SHA256: &str = "ca6bdd8786588a11b8b0713d697a211a703f688e20776d2d1cb5054dc749f139";
/// Each release-reviewed executable keeps its own exact generated schema.
/// Catalog candidates must match the current schema; older schema versions
/// are supported only for the explicit executable/version pair below.
pub const REVIEWED_BUILDS: &[(&str, &str, &str)] = &[
    (VERSION, BINARY_SHA256, SCHEMA_SHA256),
    (
        "0.159.3",
        "4d210f7c5a18fd0386434df23b5bdbb8c0e7257d3e8a2b30b0769c8bbe99a878",
        "ca6bdd8786588a11b8b0713d697a211a703f688e20776d2d1cb5054dc749f139",
    ),
    (
        "0.158.0",
        "788a818fbb9596869c7a487554507cb8bdca17584b8671112b23f9e225ba35c8",
        "b245d4b027cf8d1624c0c6733e6918c042bc278886251e7f2d90a3f29abfac2d",
    ),
    (
        "0.157.1",
        "27ceb5f9b957b43a519efe4eaa3816a0bffb0a531a2c89af18840c0a3c016a7d",
        "4da87cc14ef44c732db3404c0704a5eb902bb3a271151762052a785fdb2be056",
    ),
    (
        "0.156.1",
        "0196e89fe5a7598f816ee54232c3d7c26d75e502ab5cfe2c9240e81d90f7255a",
        "0f15f18e41d59367b3655adac23fe1525be483dc38f6fd56d07fc627eb802129",
    ),
];
pub const QUALIFIED_MODELS: &[&str] = &["gpt-6-astra", "gpt-6-sol", "gpt-5.6-sol"];
pub const ARGS: &[&str] = &["app-server", "--strict-config", "--listen", "stdio://"];
pub const ACCOUNT_FEATURES: &[&str] = &[
    "apps",
    "auth_elicitation",
    "browser_use",
    "code_mode",
    "computer_use",
    "daemon_auto_start",
    "guardian_reuse_parent_compaction",
    "guardianv2.thread_context",
    "hooks",
    "image_generation",
    "in_app_browser",
    "memories",
    "multi_agent",
    "multi_agent_v2",
    "plugins",
    "plugin_sharing",
    "realtime_conversation",
    "remote_plugin",
    "remote_control",
    "shell_snapshot",
    "shell_tool",
    "skill_mcp_dependency_install",
    "skill_search",
    "system_proxy_fallback",
    "unified_exec",
    "workspace_dependencies",
    "worktrees",
];
const EXTRA_FEATURES: &[&str] = &[
    "browser_use_external",
    "browser_use_full_cdp_access",
    "code_mode_host",
    "code_mode_only",
    "goals",
    "sleep_tool",
    "tool_suggest",
    "view_image",
    "context_management",
    "token_budget",
    "current_time_reminder",
    "deferred_executor",
    "request_permissions_tool",
];

pub fn version_admitted(version: &str) -> bool {
    REVIEWED_BUILDS
        .iter()
        .any(|(reviewed, _, _)| *reviewed == version)
}
pub fn runtime_admitted(pin: &Pin) -> Result<()> {
    if pin.provider != Provider::Codex
        || !REVIEWED_BUILDS
            .iter()
            .any(|(version, sha256, _)| *version == pin.version && *sha256 == pin.sha256)
    {
        return Err(Error::Unavailable(
            "Codex build has no broker-only qualification; install the qualified build and run xcb doctor",
        ));
    }
    Ok(())
}

/// Accept the baked release builds and exact provider binaries that the
/// reviewed-builds catalog has admitted. The catalog is intentionally an
/// exact `(version, sha256)` allowlist: it makes compatible Codex updates
/// usable without waiting for an xcb release while keeping protocol changes,
/// unknown bytes, and explicitly denied builds unavailable.
pub fn runtime_admitted_with_catalog(root: &Path, pin: &Pin) -> Result<()> {
    if crate::catalog::denied(root, &pin.sha256) {
        return Err(Error::Unavailable(
            "Codex build is denied by the reviewed-builds catalog",
        ));
    }
    if runtime_admitted(pin).is_ok()
        || (pin.provider == Provider::Codex
            && crate::catalog::admitted(root, Provider::Codex, &pin.version, &pin.sha256))
    {
        return Ok(());
    }
    Err(Error::Unavailable(
        "Codex build has no broker-only qualification; install the qualified build and run xcb doctor",
    ))
}

/// Construction is restricted to checked runtime metadata. This binds the
/// catalog bytes; the host still owns OS confinement and live qualification.
#[derive(Debug, Clone)]
pub struct Admission {
    pub(crate) catalog_sha256: String,
    // Read by the launch path and its tests, which Windows builds refuse.
    #[cfg_attr(windows, allow(dead_code))]
    pub(crate) models: BTreeSet<String>,
}
#[derive(Debug)]
pub struct StaticCatalog {
    pub bytes: Vec<u8>,
    pub sha256: String,
    pub admission: Admission,
}

#[cfg(test)]
fn catalog_from_bytes(
    binary: &[u8],
    selected: Option<&str>,
    expected_sha256: &str,
) -> Result<StaticCatalog> {
    transform_catalog(
        catalog_source_from_bytes(binary, expected_sha256)?,
        selected,
        false,
    )
}

/// Locate and parse the bundled catalog inside the admitted executable. The
/// byte digest check stays here so every caller — cached or not — still
/// proves the exact installed bytes produced the catalog.
fn catalog_source_from_bytes(binary: &[u8], expected_sha256: &str) -> Result<Value> {
    if binary.len() > 512 * 1024 * 1024 || digest(binary) != expected_sha256 {
        return Err(Error::Unavailable(
            "Codex executable changed during catalog extraction",
        ));
    }
    let marker = b"{\n  \"models\":";
    let mut matches = binary
        .windows(marker.len())
        .enumerate()
        .filter(|(_, s)| *s == marker);
    let offset = matches
        .next()
        .map(|(i, _)| i)
        .ok_or(Error::Protocol("Codex bundled model catalog absent"))?;
    if matches.next().is_some() {
        return Err(Error::Protocol("ambiguous Codex model catalog"));
    }
    let end = (offset + 4 * 1024 * 1024).min(binary.len());
    let mut stream =
        serde_json::Deserializer::from_slice(&binary[offset..end]).into_iter::<Value>();
    stream
        .next()
        .ok_or(Error::Protocol("Codex model catalog absent"))?
        .map_err(Error::from)
}

fn transform_catalog(
    source: Value,
    selected: Option<&str>,
    native_cua: bool,
) -> Result<StaticCatalog> {
    let rows = source
        .get("models")
        .and_then(Value::as_array)
        .filter(|rows| !rows.is_empty() && rows.len() <= 256)
        .ok_or(Error::Protocol("Codex model catalog shape"))?;
    let mut seen = BTreeSet::new();
    let mut result = Vec::new();
    for row in rows {
        let slug = row
            .get("slug")
            .and_then(Value::as_str)
            .filter(|s| !s.is_empty() && s.len() <= 160)
            .ok_or(Error::Protocol("Codex model slug"))?;
        if !seen.insert(slug.to_owned()) {
            return Err(Error::Protocol("duplicate Codex model"));
        }
        // Unqualified models are deliberately absent from selectable metadata.
        if !QUALIFIED_MODELS.contains(&slug) || selected.is_some_and(|wanted| wanted != slug) {
            continue;
        }
        // The pinned model must already support Node REPL. Native CUA needs
        // that real capability in its turn metadata; never invent support
        // for an absent or disabled capability in an upstream model row.
        if native_cua && row.get("node_repl_disabled") != Some(&json!(false)) {
            continue;
        }
        for field in [
            "display_name",
            "supported_reasoning_levels",
            "shell_type",
            "visibility",
            "priority",
            "supported_in_api",
            "support_verbosity",
            "truncation_policy",
            "experimental_supported_tools",
        ] {
            if row.get(field).is_none() {
                return Err(Error::Protocol("incomplete Codex model metadata"));
            }
        }
        let mut row = row
            .as_object()
            .cloned()
            .ok_or(Error::Protocol("Codex model metadata"))?;
        // Exact 0.159.0's native children cannot use this broker lane:
        // fork_turns=none drops dynamic tools, while fork_turns=all requires
        // a persisted rollout that the ephemeral root deliberately lacks.
        // Keep delegation disabled until an exact-build probe demonstrates
        // inherited broker tools without changing that storage boundary.
        for (key, value) in [
            ("tool_mode", json!("direct")),
            ("shell_type", json!("disabled")),
            ("apply_patch_tool_type", Value::Null),
            ("experimental_supported_tools", json!([])),
            ("supports_search_tool", json!(false)),
            ("supports_experimental_context", json!(false)),
            ("multi_agent_version", json!("disabled")),
            ("node_repl_disabled", json!(!native_cua)),
        ] {
            row.insert(key.into(), value);
        }
        result.push(Value::Object(row));
    }
    if result.is_empty() {
        return Err(Error::Unavailable(if native_cua {
            "Codex model lacks pinned native-computer support"
        } else {
            "Codex model lacks exact-build broker-only qualification"
        }));
    }
    let models = result
        .iter()
        .filter_map(|r| r["slug"].as_str().map(str::to_owned))
        .collect();
    let bytes = serde_json::to_vec(&json!({"models":result}))?;
    let sha256 = digest(&bytes);
    Ok(StaticCatalog {
        admission: Admission {
            catalog_sha256: sha256.clone(),
            models,
        },
        bytes,
        sha256,
    })
}

/// The extracted bundled catalog kept under the private providers state dir
/// as `codex-catalog-<binary sha256>.json`, with the digests recorded inside.
/// The file is derived state: it is used only when the recorded executable
/// digest equals the verified pin's, and is otherwise re-derived.
#[derive(Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
struct CachedCatalog {
    binary_sha256: String,
    source_sha256: String,
    source_base64: String,
}

fn catalog_cache_path(root: &Path, expected_sha256: &str) -> Result<PathBuf> {
    if !xcb_core::hex64(expected_sha256) {
        return Err(Error::Unavailable("executable digest is invalid"));
    }
    Ok(private::directory(&root.join("providers"))?
        .join(format!("codex-catalog-{expected_sha256}.json")))
}

fn cached_catalog_source(path: &Path, expected_sha256: &str) -> Option<Value> {
    let record: CachedCatalog =
        serde_json::from_slice(&private::read(path, 8 * 1024 * 1024).ok()?).ok()?;
    if record.binary_sha256 != expected_sha256 {
        return None;
    }
    let source = base64::engine::general_purpose::STANDARD
        .decode(record.source_base64.as_bytes())
        .ok()?;
    if source.len() > 4 * 1024 * 1024 || digest(&source) != record.source_sha256 {
        return None;
    }
    serde_json::from_slice(&source).ok()
}

fn store_catalog_source(path: &Path, expected_sha256: &str, source: &Value) -> Result<()> {
    let source = serde_json::to_vec(source)?;
    let record = CachedCatalog {
        binary_sha256: expected_sha256.to_owned(),
        source_sha256: digest(&source),
        source_base64: base64::engine::general_purpose::STANDARD.encode(source),
    };
    let bytes = serde_json::to_vec_pretty(&record)?;
    match private::read(path, 8 * 1024 * 1024) {
        Ok(old) => private::replace(path, &bytes, &digest(old)),
        Err(Error::Io(error)) if error.kind() == std::io::ErrorKind::NotFound => {
            private::create(path, &bytes)
        }
        // A cache file that fails custody is left alone and skipped; the
        // catalog is always re-derivable from the executable.
        Err(_) => Ok(()),
    }
}

/// Reads only the admitted executable, never the owner's model cache or auth.
/// No copied prompts or catalog from another Codex version are shipped by xcb.
/// The extracted catalog is cached under `root/providers/` keyed by the exact
/// executable digest, so a turn does not re-scan the binary.
pub fn static_catalog(root: &Path, pin: &Pin, selected: Option<&str>) -> Result<StaticCatalog> {
    runtime_admitted_with_catalog(root, pin)?;
    static_catalog_bound(root, pin, selected, &pin.sha256)
}

/// Only the launcher with an admitted native CUA proxy uses this catalog.
/// It retains pinned Node REPL support while leaving all other native tool
/// restrictions identical to the normal broker catalog.
#[cfg(target_os = "macos")]
pub(crate) fn static_catalog_with_native(
    root: &Path,
    pin: &Pin,
    selected: Option<&str>,
) -> Result<StaticCatalog> {
    runtime_admitted(pin)?;
    static_catalog_bound_mode(root, pin, selected, &pin.sha256, true)
}

/// The extraction path, bound to an explicit expected executable digest so a
/// synthetic build can exercise it in tests. Production admission always
/// first binds the version/digest pair through `static_catalog`.
pub(crate) fn static_catalog_bound(
    root: &Path,
    pin: &Pin,
    selected: Option<&str>,
    expected_sha256: &str,
) -> Result<StaticCatalog> {
    static_catalog_bound_mode(root, pin, selected, expected_sha256, false)
}

fn static_catalog_bound_mode(
    root: &Path,
    pin: &Pin,
    selected: Option<&str>,
    expected_sha256: &str,
    native_cua: bool,
) -> Result<StaticCatalog> {
    if pin.provider != Provider::Codex || pin.sha256 != expected_sha256 {
        return Err(Error::Unavailable("Codex build is not the admitted build"));
    }
    pin.verify()?;
    let cache = catalog_cache_path(root, expected_sha256).ok();
    if let Some(source) = cache
        .as_deref()
        .and_then(|path| cached_catalog_source(path, expected_sha256))
    {
        return transform_catalog(source, selected, native_cua);
    }
    let mut bytes = Vec::new();
    std::fs::File::open(&pin.executable)?
        .take(512 * 1024 * 1024 + 1)
        .read_to_end(&mut bytes)?;
    let source = catalog_source_from_bytes(&bytes, expected_sha256)?;
    pin.verify()?;
    if let Some(path) = cache {
        let _ = store_catalog_source(&path, expected_sha256, &source);
    }
    #[cfg(test)]
    CATALOG_EXTRACTIONS.fetch_add(1, std::sync::atomic::Ordering::Relaxed);
    transform_catalog(source, selected, native_cua)
}

/// Binary scans that produced a catalog, for cache tests.
#[cfg(test)]
static CATALOG_EXTRACTIONS: std::sync::atomic::AtomicUsize = std::sync::atomic::AtomicUsize::new(0);

#[cfg(all(test, unix))]
pub(crate) fn catalog_extractions() -> usize {
    CATALOG_EXTRACTIONS.load(std::sync::atomic::Ordering::Relaxed)
}

/// The bundled-catalog shape the extraction tests and the launch-path
/// benchmark embed in a synthetic executable.
#[cfg(test)]
pub(crate) fn fixture_catalog_source() -> Value {
    json!({"models":[{"slug":"gpt-6-astra","display_name":"Astra","supported_reasoning_levels":[],"shell_type":"unified_exec","visibility":"list","priority":0,"supported_in_api":true,"support_verbosity":true,"truncation_policy":{},"experimental_supported_tools":["native"],"node_repl_disabled":false,"use_responses_lite":true,"model_messages":{"instructions_template":"retained"}}]})
}

/// The host protects both this file and the catalog against provider writes.
/// Automatic review selects the reviewer; it does not widen the read-only
/// sandbox or admit native callbacks outside the host broker.
pub fn configuration(catalog_path: &Path) -> Result<String> {
    configuration_with_native(catalog_path, None)
}

pub(crate) fn configuration_with_native(
    catalog_path: &Path,
    native: Option<&Value>,
) -> Result<String> {
    let path = catalog_path
        .to_str()
        .filter(|s| {
            catalog_path.is_absolute() && s.len() <= 4096 && !s.chars().any(char::is_control)
        })
        .ok_or(Error::Protocol("Codex catalog path"))?;
    let mut lines = vec![format!(
        "model_catalog_json = {}",
        serde_json::to_string(path)?
    )];
    lines.extend(
        [
            "model_provider = \"openai\"",
            "forced_login_method = \"chatgpt\"",
            "cli_auth_credentials_store = \"file\"",
            "mcp_oauth_credentials_store = \"file\"",
            "approval_policy = \"on-request\"",
            "approvals_reviewer = \"auto_review\"",
            "sandbox_mode = \"read-only\"",
            "web_search = \"disabled\"",
            "project_doc_max_bytes = 0",
            "check_for_update_on_startup = false",
            "allow_login_shell = false",
            "notify = []",
            "mcp_servers = {}",
            "plugins = {}",
            "[shell_environment_policy]",
            "inherit = \"none\"",
            "[analytics]",
            "enabled = false",
            "[feedback]",
            "enabled = false",
            "[history]",
            "persistence = \"none\"",
            "[features]",
        ]
        .map(str::to_owned),
    );
    lines.extend(
        ACCOUNT_FEATURES
            .iter()
            // Feature names can contain dots; quote each TOML key so a
            // disabled feature cannot become an unrelated nested table.
            .map(|name| {
                format!(
                    "{} = false",
                    serde_json::to_string(name).expect("feature name")
                )
            }),
    );
    lines.extend(
        [
            "[apps._default]",
            "enabled = false",
            "destructive_enabled = false",
            "open_world_enabled = false",
            "[orchestrator.skills]",
            "enabled = false",
            "[skills]",
            "include_instructions = false",
            "[skills.bundled]",
            "enabled = false",
            "",
        ]
        .map(str::to_owned),
    );
    if let Some(server) = native {
        lines.retain(|line| line != "mcp_servers = {}");
        validate_native_definition(server)?;
        lines.push("[mcp_servers.cua_repl]".into());
        for key in ["command", "args", "enabled", "enabled_tools"] {
            lines.push(format!("{key} = {}", serde_json::to_string(&server[key])?));
        }
        let environment = server["env"]
            .as_object()
            .ok_or(Error::Protocol("Codex native environment"))?;
        lines.push(format!(
            "env = {{ {} }}",
            environment
                .iter()
                .map(|(name, value)| {
                    Ok(format!(
                        "{} = {}",
                        serde_json::to_string(name)?,
                        serde_json::to_string(value)?
                    ))
                })
                .collect::<Result<Vec<_>>>()?
                .join(", ")
        ));
        lines.push(String::new());
    }
    Ok(lines.join("\n"))
}

fn validate_native_definition(server: &Value) -> Result<()> {
    super::closed(
        server,
        &["command", "args", "env", "enabled", "enabled_tools"],
    )?;
    let command = server["command"]
        .as_str()
        .ok_or(Error::Protocol("Codex native command"))?;
    let env = server["env"]
        .as_object()
        .ok_or(Error::Protocol("Codex native environment"))?;
    super::require(
        Path::new(command).is_absolute()
            && command.len() <= 4096
            && !command.chars().any(char::is_control)
            && server["args"] == json!(["native-mcp-stdio"])
            && server["enabled"] == true
            && server["enabled_tools"].as_array().is_some_and(|tools| {
                !tools.is_empty()
                    && tools.len() <= 3
                    && tools.contains(&json!("js"))
                    && tools
                        .iter()
                        .all(|tool| matches!(tool.as_str(), Some("js" | "js_reset" | "turn_ended")))
                    && tools
                        .iter()
                        .filter_map(Value::as_str)
                        .collect::<BTreeSet<_>>()
                        .len()
                        == tools.len()
            })
            && env.len() == 2
            && env
                .get("XCB_MCP_SOCKET")
                .and_then(Value::as_str)
                .is_some_and(|path| {
                    Path::new(path).is_absolute()
                        && path.len() <= 100
                        && !path.chars().any(char::is_control)
                })
            && env
                .get("XCB_MCP_TOKEN")
                .and_then(Value::as_str)
                .is_some_and(|token| {
                    (32..=128).contains(&token.len())
                        && token
                            .bytes()
                            .all(|byte| byte.is_ascii_alphanumeric() || byte == b'-')
                }),
        "Codex native tool definition changed",
    )
}

pub fn thread_configuration(effort: Option<&str>) -> Value {
    let features: serde_json::Map<String, Value> = ACCOUNT_FEATURES
        .iter()
        .chain(EXTRA_FEATURES)
        .map(|name| (name.to_string(), json!(false)))
        .collect();
    let mut config = json!({"features":features,"tools":{"experimental_request_user_input":{"enabled":false},"update_plan":{"enabled":false}},"agents":{"enabled":false},"approvals_reviewer":"auto_review"});
    if let Some(effort) = effort {
        config["model_reasoning_effort"] = json!(effort);
    }
    config
}

#[cfg(all(test, unix))]
pub(crate) fn validate_config(value: &Value, catalog_path: &Path) -> Result<()> {
    validate_config_with_native(value, catalog_path, None)
}

pub(crate) fn validate_config_with_native(
    value: &Value,
    catalog_path: &Path,
    native: Option<&Value>,
) -> Result<()> {
    let c = value
        .get("config")
        .and_then(Value::as_object)
        .ok_or(Error::Protocol("Codex config response"))?;
    for (key, expected) in [
        ("model_provider", json!("openai")),
        ("forced_login_method", json!("chatgpt")),
        ("cli_auth_credentials_store", json!("file")),
        ("mcp_oauth_credentials_store", json!("file")),
        ("approval_policy", json!("on-request")),
        ("approvals_reviewer", json!("auto_review")),
        ("sandbox_mode", json!("read-only")),
        ("web_search", json!("disabled")),
        ("project_doc_max_bytes", json!(0)),
        ("check_for_update_on_startup", json!(false)),
        ("allow_login_shell", json!(false)),
        ("notify", json!([])),
        ("plugins", json!({})),
        ("model_providers", json!({})),
        ("model_catalog_json", json!(catalog_path)),
    ] {
        if c.get(key) != Some(&expected) {
            return Err(Error::Protocol("Codex isolated configuration mismatch"));
        }
    }
    match native {
        None if c.get("mcp_servers") != Some(&json!({})) => {
            return Err(Error::Protocol("Codex unexpected native servers"));
        }
        Some(expected) => {
            validate_native_definition(expected)?;
            let servers = c
                .get("mcp_servers")
                .and_then(Value::as_object)
                .filter(|servers| servers.len() == 1)
                .ok_or(Error::Protocol("Codex native server inventory changed"))?;
            let actual = servers
                .get("cua_repl")
                .ok_or(Error::Protocol("Codex native server missing"))?;
            let mut expected = expected.clone();
            expected["environment_id"] = json!("local");
            expected["tool_timeout_sec"] = Value::Null;
            if actual != &expected {
                return Err(Error::Protocol("Codex native server controls changed"));
            }
        }
        None => {}
    }
    if c.get("chatgpt_base_url") != Some(&json!("https://chatgpt.com/backend-api/")) {
        return Err(Error::Protocol("Codex ChatGPT endpoint changed"));
    }
    for key in [
        "instructions",
        "developer_instructions",
        "compact_prompt",
        "model_instructions_file",
        "experimental_compact_prompt_file",
        "openai_base_url",
    ] {
        if c.get(key).is_some_and(|v| !v.is_null()) {
            return Err(Error::Protocol("Codex inherited instructions or endpoint"));
        }
    }
    let v = Value::Object(c.clone());
    for (pointer, expected) in [
        ("/shell_environment_policy/inherit", json!("none")),
        ("/analytics/enabled", json!(false)),
        ("/feedback/enabled", json!(false)),
        ("/history/persistence", json!("none")),
        ("/skills/include_instructions", json!(false)),
        ("/skills/bundled/enabled", json!(false)),
        ("/orchestrator/skills/enabled", json!(false)),
        ("/apps/_default/enabled", json!(false)),
        ("/apps/_default/destructive_enabled", json!(false)),
        ("/apps/_default/open_world_enabled", json!(false)),
    ] {
        if v.pointer(pointer) != Some(&expected) {
            return Err(Error::Protocol("Codex configuration controls mismatch"));
        }
    }
    if v["apps"].as_object().is_none_or(|a| a.len() != 1) {
        return Err(Error::Protocol("Codex inherited apps"));
    }
    for name in ACCOUNT_FEATURES {
        if v["features"].get(name) != Some(&json!(false)) {
            return Err(Error::Protocol("Codex account feature enabled"));
        }
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn catalog_preserves_native_protocol_and_metadata() {
        let source = fixture_catalog_source();
        let catalog = transform_catalog(source, Some("gpt-6-astra"), false).unwrap();
        let row: Value = serde_json::from_slice(&catalog.bytes).unwrap();
        assert_eq!(
            row["models"][0]["model_messages"]["instructions_template"],
            "retained"
        );
        assert_eq!(row["models"][0]["use_responses_lite"], true);
        assert_eq!(row["models"][0]["shell_type"], "disabled");
        assert_eq!(row["models"][0]["multi_agent_version"], "disabled");
        assert_eq!(row["models"][0]["experimental_supported_tools"], json!([]));
        assert!(transform_catalog(row, Some("unqualified"), false).is_err());
    }
    #[test]
    fn untested_builds_and_forged_catalogs_are_not_admitted() {
        assert!(version_admitted(VERSION));
        assert!(!version_admitted("0.155.1"));
        assert!(!version_admitted("0.155.0-alpha.2.6"));
        assert!(catalog_from_bytes(b"{\n  \"models\":[]}", None, BINARY_SHA256).is_err());
    }

    #[test]
    fn supported_versions_are_bound_to_their_own_executable_and_schema() {
        for (version, sha256, schema) in REVIEWED_BUILDS {
            assert!(version_admitted(version));
            assert_eq!(schema.len(), 64);
            let mut pin = Pin {
                provider: Provider::Codex,
                executable: "/synthetic/codex".into(),
                sha256: (*sha256).into(),
                version: (*version).into(),
                host_sha256: "0".repeat(64),
                observed_at_ms: 0,
            };
            runtime_admitted(&pin).unwrap();
            pin.sha256 = "f".repeat(64);
            assert!(runtime_admitted(&pin).is_err());
            pin.sha256 = (*sha256).into();
            pin.version = "0.0.0".into();
            assert!(runtime_admitted(&pin).is_err());
        }
        // Distinct versions may share a schema when the generated schema is
        // unchanged; version and executable digests stay unique.
        let versions: BTreeSet<_> = REVIEWED_BUILDS.iter().map(|(v, _, _)| v).collect();
        let executables: BTreeSet<_> = REVIEWED_BUILDS.iter().map(|(_, s, _)| s).collect();
        assert_eq!(versions.len(), REVIEWED_BUILDS.len());
        assert_eq!(executables.len(), REVIEWED_BUILDS.len());
    }

    #[test]
    fn native_catalog_retains_only_pinned_node_support_and_no_other_authority() {
        let source = fixture_catalog_source();
        let normal = transform_catalog(source.clone(), Some("gpt-6-astra"), false).unwrap();
        let native = transform_catalog(source.clone(), Some("gpt-6-astra"), true).unwrap();
        assert_ne!(normal.sha256, native.sha256);
        assert_eq!(native.admission.catalog_sha256, digest(&native.bytes));
        let normal: Value = serde_json::from_slice(&normal.bytes).unwrap();
        let mut native: Value = serde_json::from_slice(&native.bytes).unwrap();
        assert_eq!(normal["models"][0]["node_repl_disabled"], true);
        assert_eq!(native["models"][0]["node_repl_disabled"], false);
        native["models"][0]["node_repl_disabled"] = json!(true);
        assert_eq!(normal, native);
        assert_eq!(native["models"][0]["shell_type"], "disabled");
        assert_eq!(
            native["models"][0]["experimental_supported_tools"],
            json!([])
        );
        assert_eq!(native["models"][0]["multi_agent_version"], "disabled");
        assert!(native["models"][0]["apply_patch_tool_type"].is_null());
        for unsupported in [json!(true), Value::Null, json!("false")] {
            let mut changed = source.clone();
            changed["models"][0]["node_repl_disabled"] = unsupported;
            assert!(transform_catalog(changed, Some("gpt-6-astra"), true).is_err());
        }
    }

    #[test]
    fn catalog_admission_reaches_the_launch_gate_without_becoming_fail_open() {
        let directory = tempfile::tempdir().unwrap();
        let root = xcb_core::canonical(directory.path()).unwrap();
        private::directory(&root.join("providers")).unwrap();
        let digest = "a".repeat(64);
        private::create(
            &root.join("providers/catalog.json"),
            serde_json::json!({
                "version": 1,
                "codex": [{"version": "0.160.0", "sha256": digest.clone()}],
            })
            .to_string()
            .as_bytes(),
        )
        .unwrap();
        let pin = Pin {
            provider: Provider::Codex,
            executable: "/synthetic/codex".into(),
            sha256: digest.clone(),
            version: "0.160.0".into(),
            host_sha256: "0".repeat(64),
            observed_at_ms: 0,
        };
        runtime_admitted_with_catalog(&root, &pin).unwrap();

        let mut unknown = pin.clone();
        unknown.version = "0.160.1".into();
        assert!(runtime_admitted_with_catalog(&root, &unknown).is_err());

        private::replace(
            &root.join("providers/catalog.json"),
            serde_json::json!({
                "version": 1,
                "codex": [{"version": "0.160.0", "sha256": digest.clone()}],
                "deny": {"codex": [digest.clone()]},
            })
            .to_string()
            .as_bytes(),
            &crate::digest(
                &private::read(&root.join("providers/catalog.json"), 64 * 1024).unwrap(),
            ),
        )
        .unwrap();
        assert!(runtime_admitted_with_catalog(&root, &pin).is_err());
    }

    // Unix catalog paths; Codex launch is refused on Windows.
    #[cfg(unix)]
    #[test]
    fn background_features_are_disabled_as_literal_toml_keys() {
        let config = configuration(Path::new("/synthetic/catalog.json")).unwrap();
        for name in ["daemon_auto_start", "guardianv2.thread_context"] {
            assert!(config.contains(&format!("\"{name}\" = false")));
            assert_eq!(thread_configuration(None)["features"][name], false);
        }
    }

    #[cfg(unix)]
    #[test]
    fn catalog_cache_is_keyed_by_the_exact_executable_digest() {
        use std::os::unix::fs::PermissionsExt;
        let directory = tempfile::tempdir().unwrap();
        let root = xcb_core::canonical(directory.path()).unwrap();
        let executable = root.join("codex");
        let mut bytes = b"synthetic codex binary\n".to_vec();
        bytes.extend(serde_json::to_vec_pretty(&fixture_catalog_source()).unwrap());
        bytes.push(0);
        std::fs::write(&executable, &bytes).unwrap();
        std::fs::set_permissions(&executable, std::fs::Permissions::from_mode(0o755)).unwrap();
        let executable = xcb_core::canonical(executable).unwrap();
        let sha256 = crate::process::executable_digest(&executable).unwrap();
        let (_, host_sha256) = crate::process::host_identity().unwrap();
        let pin = Pin {
            provider: Provider::Codex,
            executable,
            sha256: sha256.clone(),
            version: VERSION.into(),
            host_sha256,
            observed_at_ms: crate::now_ms(),
        };
        let cache = root
            .join("providers")
            .join(format!("codex-catalog-{sha256}.json"));
        let extracted = catalog_extractions();
        let first = static_catalog_bound(&root, &pin, Some("gpt-6-astra"), &sha256).unwrap();
        assert!(cache.is_file());
        let second = static_catalog_bound(&root, &pin, Some("gpt-6-astra"), &sha256).unwrap();
        assert_eq!(first.sha256, second.sha256);
        assert_eq!(first.bytes, second.bytes);
        assert_eq!(catalog_extractions() - extracted, 1);
        let native =
            static_catalog_bound_mode(&root, &pin, Some("gpt-6-astra"), &sha256, true).unwrap();
        assert_ne!(native.sha256, first.sha256);
        assert_eq!(catalog_extractions() - extracted, 1);
        assert_eq!(
            static_catalog_bound(&root, &pin, Some("gpt-6-astra"), &sha256)
                .unwrap()
                .sha256,
            first.sha256
        );
        // A corrupted cache file is derived state: it is ignored, re-extracted,
        // and republished, never admitted.
        std::fs::write(&cache, b"not a catalog").unwrap();
        let third = static_catalog_bound(&root, &pin, Some("gpt-6-astra"), &sha256).unwrap();
        assert_eq!(third.sha256, first.sha256);
        assert_eq!(catalog_extractions() - extracted, 2);
    }
}
