use crate::{Error, Result, digest, private, process::Pin};
use base64::Engine;
use serde::{Deserialize, Serialize};
use serde_json::{Value, json};
use std::{
    collections::BTreeSet,
    io::Read,
    path::{Path, PathBuf},
};
use xcb_core::Provider;

pub const VERSION: &str = "0.155.0-alpha.2.6";
pub const BINARY_SHA256: &str = "805f2102d573c580d8cad2fc774b81837e68f7e9bdd1adb559d67801bbc1f9bd";
/// Sorted relative schema path, NUL, generated bytes, NUL for each JSON file.
pub const SCHEMA_SHA256: &str = "d529eb8854fecb8508f8e047fdcfe6aaff2aae0e1b84b5eb2c91c6301b02e82d";
pub const QUALIFIED_MODELS: &[&str] = &["gpt-6-astra", "gpt-5.6-sol"];
pub const ARGS: &[&str] = &["app-server", "--strict-config", "--listen", "stdio://"];
pub const ACCOUNT_FEATURES: &[&str] = &[
    "apps",
    "auth_elicitation",
    "browser_use",
    "code_mode",
    "computer_use",
    "hooks",
    "image_generation",
    "in_app_browser",
    "memories",
    "multi_agent",
    "multi_agent_v2",
    "plugins",
    "plugin_sharing",
    "remote_plugin",
    "remote_control",
    "shell_snapshot",
    "shell_tool",
    "skill_mcp_dependency_install",
    "skill_search",
    "unified_exec",
    "workspace_dependencies",
];
const EXTRA_FEATURES: &[&str] = &[
    "browser_use_external",
    "browser_use_full_cdp_access",
    "code_mode_host",
    "code_mode_only",
    "goals",
    "sleep_tool",
    "tool_suggest",
    "view_image",
    "context_management",
    "token_budget",
    "current_time_reminder",
    "deferred_executor",
    "request_permissions_tool",
];

pub fn version_admitted(version: &str) -> bool {
    version == VERSION
}
pub fn runtime_admitted(pin: &Pin) -> Result<()> {
    if pin.provider != Provider::Codex
        || !version_admitted(&pin.version)
        || pin.sha256 != BINARY_SHA256
    {
        return Err(Error::Unavailable(
            "Codex build has no broker-only qualification; install the qualified build and run xcb doctor",
        ));
    }
    Ok(())
}

/// Construction is restricted to checked runtime metadata. This binds the
/// catalog bytes; the host still owns OS confinement and live qualification.
#[derive(Debug, Clone)]
pub struct Admission {
    pub(crate) catalog_sha256: String,
    pub(crate) models: BTreeSet<String>,
}
#[derive(Debug)]
pub struct StaticCatalog {
    pub bytes: Vec<u8>,
    pub sha256: String,
    pub admission: Admission,
}

#[cfg(test)]
fn catalog_from_bytes(
    binary: &[u8],
    selected: Option<&str>,
    expected_sha256: &str,
) -> Result<StaticCatalog> {
    transform_catalog(
        catalog_source_from_bytes(binary, expected_sha256)?,
        selected,
    )
}

/// Locate and parse the bundled catalog inside the admitted executable. The
/// byte digest check stays here so every caller — cached or not — still
/// proves the exact installed bytes produced the catalog.
fn catalog_source_from_bytes(binary: &[u8], expected_sha256: &str) -> Result<Value> {
    if binary.len() > 512 * 1024 * 1024 || digest(binary) != expected_sha256 {
        return Err(Error::Unavailable(
            "Codex executable changed during catalog extraction",
        ));
    }
    let marker = b"{\n  \"models\":";
    let mut matches = binary
        .windows(marker.len())
        .enumerate()
        .filter(|(_, s)| *s == marker);
    let offset = matches
        .next()
        .map(|(i, _)| i)
        .ok_or(Error::Protocol("Codex bundled model catalog absent"))?;
    if matches.next().is_some() {
        return Err(Error::Protocol("ambiguous Codex model catalog"));
    }
    let end = (offset + 4 * 1024 * 1024).min(binary.len());
    let mut stream =
        serde_json::Deserializer::from_slice(&binary[offset..end]).into_iter::<Value>();
    stream
        .next()
        .ok_or(Error::Protocol("Codex model catalog absent"))?
        .map_err(Error::from)
}

fn transform_catalog(source: Value, selected: Option<&str>) -> Result<StaticCatalog> {
    let rows = source
        .get("models")
        .and_then(Value::as_array)
        .filter(|rows| !rows.is_empty() && rows.len() <= 256)
        .ok_or(Error::Protocol("Codex model catalog shape"))?;
    let mut seen = BTreeSet::new();
    let mut result = Vec::new();
    for row in rows {
        let slug = row
            .get("slug")
            .and_then(Value::as_str)
            .filter(|s| !s.is_empty() && s.len() <= 160)
            .ok_or(Error::Protocol("Codex model slug"))?;
        if !seen.insert(slug.to_owned()) {
            return Err(Error::Protocol("duplicate Codex model"));
        }
        // Unqualified models are deliberately absent from selectable metadata.
        if !QUALIFIED_MODELS.contains(&slug) || selected.is_some_and(|wanted| wanted != slug) {
            continue;
        }
        for field in [
            "display_name",
            "supported_reasoning_levels",
            "shell_type",
            "visibility",
            "priority",
            "supported_in_api",
            "support_verbosity",
            "truncation_policy",
            "experimental_supported_tools",
        ] {
            if row.get(field).is_none() {
                return Err(Error::Protocol("incomplete Codex model metadata"));
            }
        }
        let mut row = row
            .as_object()
            .cloned()
            .ok_or(Error::Protocol("Codex model metadata"))?;
        for (key, value) in [
            ("tool_mode", json!("direct")),
            ("shell_type", json!("disabled")),
            ("apply_patch_tool_type", Value::Null),
            ("experimental_supported_tools", json!([])),
            ("supports_search_tool", json!(false)),
            ("supports_experimental_context", json!(false)),
            ("multi_agent_version", json!("disabled")),
            ("node_repl_disabled", json!(true)),
        ] {
            row.insert(key.into(), value);
        }
        result.push(Value::Object(row));
    }
    if result.is_empty() {
        return Err(Error::Unavailable(
            "Codex model lacks exact-build broker-only qualification",
        ));
    }
    let models = result
        .iter()
        .filter_map(|r| r["slug"].as_str().map(str::to_owned))
        .collect();
    let bytes = serde_json::to_vec(&json!({"models":result}))?;
    let sha256 = digest(&bytes);
    Ok(StaticCatalog {
        admission: Admission {
            catalog_sha256: sha256.clone(),
            models,
        },
        bytes,
        sha256,
    })
}

/// The extracted bundled catalog kept under the private providers state dir
/// as `codex-catalog-<binary sha256>.json`, with the digests recorded inside.
/// The file is derived state: it is used only when the recorded executable
/// digest equals the verified pin's, and is otherwise re-derived.
#[derive(Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
struct CachedCatalog {
    binary_sha256: String,
    source_sha256: String,
    source_base64: String,
}

fn catalog_cache_path(root: &Path, expected_sha256: &str) -> Result<PathBuf> {
    if expected_sha256.len() != 64
        || !expected_sha256
            .bytes()
            .all(|byte| byte.is_ascii_hexdigit() && !byte.is_ascii_uppercase())
    {
        return Err(Error::Unavailable("executable digest is invalid"));
    }
    Ok(private::directory(&root.join("providers"))?
        .join(format!("codex-catalog-{expected_sha256}.json")))
}

fn cached_catalog_source(path: &Path, expected_sha256: &str) -> Option<Value> {
    let record: CachedCatalog =
        serde_json::from_slice(&private::read(path, 8 * 1024 * 1024).ok()?).ok()?;
    if record.binary_sha256 != expected_sha256 {
        return None;
    }
    let source = base64::engine::general_purpose::STANDARD
        .decode(record.source_base64.as_bytes())
        .ok()?;
    if source.len() > 4 * 1024 * 1024 || digest(&source) != record.source_sha256 {
        return None;
    }
    serde_json::from_slice(&source).ok()
}

fn store_catalog_source(path: &Path, expected_sha256: &str, source: &Value) -> Result<()> {
    let source = serde_json::to_vec(source)?;
    let record = CachedCatalog {
        binary_sha256: expected_sha256.to_owned(),
        source_sha256: digest(&source),
        source_base64: base64::engine::general_purpose::STANDARD.encode(source),
    };
    let bytes = serde_json::to_vec_pretty(&record)?;
    match private::read(path, 8 * 1024 * 1024) {
        Ok(old) => private::replace(path, &bytes, &digest(old)),
        Err(Error::Io(error)) if error.kind() == std::io::ErrorKind::NotFound => {
            private::create(path, &bytes)
        }
        // A cache file that fails custody is left alone and skipped; the
        // catalog is always re-derivable from the executable.
        Err(_) => Ok(()),
    }
}

/// Reads only the admitted executable, never the owner's model cache or auth.
/// No copied prompts or catalog from another Codex version are shipped by xcb.
/// The extracted catalog is cached under `root/providers/` keyed by the exact
/// executable digest, so a turn does not re-scan the binary.
pub fn static_catalog(root: &Path, pin: &Pin, selected: Option<&str>) -> Result<StaticCatalog> {
    runtime_admitted(pin)?;
    static_catalog_bound(root, pin, selected, BINARY_SHA256)
}

/// The extraction path, bound to an explicit expected executable digest so a
/// synthetic build can exercise it in tests. Production admission always
/// passes `BINARY_SHA256` through `static_catalog`.
pub(crate) fn static_catalog_bound(
    root: &Path,
    pin: &Pin,
    selected: Option<&str>,
    expected_sha256: &str,
) -> Result<StaticCatalog> {
    if pin.provider != Provider::Codex || pin.sha256 != expected_sha256 {
        return Err(Error::Unavailable("Codex build is not the admitted build"));
    }
    pin.verify()?;
    let cache = catalog_cache_path(root, expected_sha256).ok();
    if let Some(source) = cache
        .as_deref()
        .and_then(|path| cached_catalog_source(path, expected_sha256))
    {
        return transform_catalog(source, selected);
    }
    let mut bytes = Vec::new();
    std::fs::File::open(&pin.executable)?
        .take(512 * 1024 * 1024 + 1)
        .read_to_end(&mut bytes)?;
    let source = catalog_source_from_bytes(&bytes, expected_sha256)?;
    pin.verify()?;
    if let Some(path) = cache {
        let _ = store_catalog_source(&path, expected_sha256, &source);
    }
    #[cfg(test)]
    CATALOG_EXTRACTIONS.fetch_add(1, std::sync::atomic::Ordering::Relaxed);
    transform_catalog(source, selected)
}

/// Binary scans that produced a catalog, for cache tests.
#[cfg(test)]
static CATALOG_EXTRACTIONS: std::sync::atomic::AtomicUsize = std::sync::atomic::AtomicUsize::new(0);

#[cfg(test)]
pub(crate) fn catalog_extractions() -> usize {
    CATALOG_EXTRACTIONS.load(std::sync::atomic::Ordering::Relaxed)
}

/// The bundled-catalog shape the extraction tests and the launch-path
/// benchmark embed in a synthetic executable.
#[cfg(test)]
pub(crate) fn fixture_catalog_source() -> Value {
    json!({"models":[{"slug":"gpt-6-astra","display_name":"Astra","supported_reasoning_levels":[],"shell_type":"unified_exec","visibility":"list","priority":0,"supported_in_api":true,"support_verbosity":true,"truncation_policy":{},"experimental_supported_tools":["native"],"use_responses_lite":true,"model_messages":{"instructions_template":"retained"}}]})
}

/// The host protects both this file and the catalog against provider writes.
pub fn configuration(catalog_path: &Path) -> Result<String> {
    let path = catalog_path
        .to_str()
        .filter(|s| {
            catalog_path.is_absolute() && s.len() <= 4096 && !s.chars().any(char::is_control)
        })
        .ok_or(Error::Protocol("Codex catalog path"))?;
    let mut lines = vec![format!(
        "model_catalog_json = {}",
        serde_json::to_string(path)?
    )];
    lines.extend(
        [
            "model_provider = \"openai\"",
            "forced_login_method = \"chatgpt\"",
            "cli_auth_credentials_store = \"file\"",
            "mcp_oauth_credentials_store = \"file\"",
            "approval_policy = \"never\"",
            "sandbox_mode = \"read-only\"",
            "web_search = \"disabled\"",
            "project_doc_max_bytes = 0",
            "check_for_update_on_startup = false",
            "allow_login_shell = false",
            "notify = []",
            "mcp_servers = {}",
            "plugins = {}",
            "[shell_environment_policy]",
            "inherit = \"none\"",
            "[analytics]",
            "enabled = false",
            "[feedback]",
            "enabled = false",
            "[history]",
            "persistence = \"none\"",
            "[features]",
        ]
        .map(str::to_owned),
    );
    lines.extend(
        ACCOUNT_FEATURES
            .iter()
            .map(|name| format!("{name} = false")),
    );
    lines.extend(
        [
            "[apps._default]",
            "enabled = false",
            "destructive_enabled = false",
            "open_world_enabled = false",
            "[orchestrator.skills]",
            "enabled = false",
            "[skills]",
            "include_instructions = false",
            "[skills.bundled]",
            "enabled = false",
            "",
        ]
        .map(str::to_owned),
    );
    Ok(lines.join("\n"))
}

pub fn thread_configuration(effort: Option<&str>) -> Value {
    let features: serde_json::Map<String, Value> = ACCOUNT_FEATURES
        .iter()
        .chain(EXTRA_FEATURES)
        .map(|name| (name.to_string(), json!(false)))
        .collect();
    let mut config = json!({"features":features,"tools":{"experimental_request_user_input":{"enabled":false},"update_plan":{"enabled":false}},"agents":{"enabled":false}});
    if let Some(effort) = effort {
        config["model_reasoning_effort"] = json!(effort);
    }
    config
}

pub(crate) fn validate_config(value: &Value, catalog_path: &Path) -> Result<()> {
    let c = value
        .get("config")
        .and_then(Value::as_object)
        .ok_or(Error::Protocol("Codex config response"))?;
    for (key, expected) in [
        ("model_provider", json!("openai")),
        ("forced_login_method", json!("chatgpt")),
        ("cli_auth_credentials_store", json!("file")),
        ("mcp_oauth_credentials_store", json!("file")),
        ("approval_policy", json!("never")),
        ("sandbox_mode", json!("read-only")),
        ("web_search", json!("disabled")),
        ("project_doc_max_bytes", json!(0)),
        ("check_for_update_on_startup", json!(false)),
        ("allow_login_shell", json!(false)),
        ("notify", json!([])),
        ("mcp_servers", json!({})),
        ("plugins", json!({})),
        ("model_providers", json!({})),
        ("model_catalog_json", json!(catalog_path)),
    ] {
        if c.get(key) != Some(&expected) {
            return Err(Error::Protocol("Codex isolated configuration mismatch"));
        }
    }
    if c.get("chatgpt_base_url") != Some(&json!("https://chatgpt.com/backend-api/")) {
        return Err(Error::Protocol("Codex ChatGPT endpoint changed"));
    }
    for key in [
        "instructions",
        "developer_instructions",
        "compact_prompt",
        "model_instructions_file",
        "experimental_compact_prompt_file",
        "openai_base_url",
    ] {
        if c.get(key).is_some_and(|v| !v.is_null()) {
            return Err(Error::Protocol("Codex inherited instructions or endpoint"));
        }
    }
    let v = Value::Object(c.clone());
    for (pointer, expected) in [
        ("/shell_environment_policy/inherit", json!("none")),
        ("/analytics/enabled", json!(false)),
        ("/feedback/enabled", json!(false)),
        ("/history/persistence", json!("none")),
        ("/skills/include_instructions", json!(false)),
        ("/skills/bundled/enabled", json!(false)),
        ("/orchestrator/skills/enabled", json!(false)),
        ("/apps/_default/enabled", json!(false)),
        ("/apps/_default/destructive_enabled", json!(false)),
        ("/apps/_default/open_world_enabled", json!(false)),
    ] {
        if v.pointer(pointer) != Some(&expected) {
            return Err(Error::Protocol("Codex configuration controls mismatch"));
        }
    }
    if v["apps"].as_object().is_none_or(|a| a.len() != 1) {
        return Err(Error::Protocol("Codex inherited apps"));
    }
    for name in ACCOUNT_FEATURES {
        if v["features"].get(name) != Some(&json!(false)) {
            return Err(Error::Protocol("Codex account feature enabled"));
        }
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn catalog_preserves_native_protocol_and_metadata() {
        let source = fixture_catalog_source();
        let catalog = transform_catalog(source, Some("gpt-6-astra")).unwrap();
        let row: Value = serde_json::from_slice(&catalog.bytes).unwrap();
        assert_eq!(
            row["models"][0]["model_messages"]["instructions_template"],
            "retained"
        );
        assert_eq!(row["models"][0]["use_responses_lite"], true);
        assert_eq!(row["models"][0]["shell_type"], "disabled");
        assert_eq!(row["models"][0]["multi_agent_version"], "disabled");
        assert_eq!(row["models"][0]["experimental_supported_tools"], json!([]));
        assert!(transform_catalog(row, Some("unqualified")).is_err());
    }
    #[test]
    fn untested_builds_and_forged_catalogs_are_not_admitted() {
        assert!(version_admitted(VERSION));
        assert!(!version_admitted("0.155.1"));
        assert!(catalog_from_bytes(b"{\n  \"models\":[]}", None, BINARY_SHA256).is_err());
    }

    #[test]
    fn catalog_cache_is_keyed_by_the_exact_executable_digest() {
        use std::os::unix::fs::PermissionsExt;
        let directory = tempfile::tempdir().unwrap();
        let root = directory.path().canonicalize().unwrap();
        let executable = root.join("codex");
        let mut bytes = b"synthetic codex binary\n".to_vec();
        bytes.extend(serde_json::to_vec_pretty(&fixture_catalog_source()).unwrap());
        bytes.push(0);
        std::fs::write(&executable, &bytes).unwrap();
        std::fs::set_permissions(&executable, std::fs::Permissions::from_mode(0o755)).unwrap();
        let executable = executable.canonicalize().unwrap();
        let sha256 = crate::process::executable_digest(&executable).unwrap();
        let (_, host_sha256) = crate::process::host_identity().unwrap();
        let pin = Pin {
            provider: Provider::Codex,
            executable,
            sha256: sha256.clone(),
            version: VERSION.into(),
            host_sha256,
            observed_at_ms: crate::now_ms(),
        };
        let cache = root
            .join("providers")
            .join(format!("codex-catalog-{sha256}.json"));
        let extracted = catalog_extractions();
        let first = static_catalog_bound(&root, &pin, Some("gpt-6-astra"), &sha256).unwrap();
        assert!(cache.is_file());
        let second = static_catalog_bound(&root, &pin, Some("gpt-6-astra"), &sha256).unwrap();
        assert_eq!(first.sha256, second.sha256);
        assert_eq!(first.bytes, second.bytes);
        assert_eq!(catalog_extractions() - extracted, 1);
        // A corrupted cache file is derived state: it is ignored, re-extracted,
        // and republished, never admitted.
        std::fs::write(&cache, b"not a catalog").unwrap();
        let third = static_catalog_bound(&root, &pin, Some("gpt-6-astra"), &sha256).unwrap();
        assert_eq!(third.sha256, first.sha256);
        assert_eq!(catalog_extractions() - extracted, 2);
    }
}
