[package]
name = "xcb-tui"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
arboard = "=3.6.1"
crossterm = "=0.29.0"
ratatui = { version = "=0.30.2", default-features = false, features = ["crossterm", "underline-color", "layout-cache"] }
ratatui-textarea = "=0.9.2"
serde_json = "=1.0.151"
unicode-segmentation = "=1.13.3"
rustix = { version = "=1.1.5", features = ["fs", "process"] }
uuid = { version = "=1.26.1", features = ["v4"] }
xcb-core = { version = "0.8.6", path = "../xcb-core" }
